FROM golang:1.16

WORKDIR /usr/src/app

COPY material-applications/example-backend/go.mod \
     material-applications/example-backend/go.sum ./

RUN go mod download

COPY material-applications/example-backend .

RUN go build -o server

EXPOSE 8080

ENV PORT=8080
ENV REQUEST_ORIGIN=http://localhost:5000

CMD [ "./server" ]