FROM node:16

EXPOSE 5000
ENV REACT_APP_BACKEND_URL=http://localhost:8080
WORKDIR /usr/src/app

COPY material-applications/example-frontend/package*.json ./

RUN npm install

COPY material-applications/example-frontend .
RUN npm install -g serve


RUN npm run build

CMD [ "serve", "-s", "-l", "5000", "build" ]