FROM golang:1.16-alpine

WORKDIR /usr/src/app

COPY example-backend/go.mod \
     example-backend/go.sum ./

RUN go mod download

COPY example-backend .

RUN go build -o server

EXPOSE 8080

ENV PORT=8080
ENV REQUEST_ORIGIN=http://localhost:5001

CMD [ "./server" ]