FROM golang:1.16-alpine AS build-stage

WORKDIR /app

COPY example-backend/go.mod example-backend/go.sum ./
RUN go mod download

COPY example-backend .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -o server


FROM scratch

WORKDIR /app

COPY --from=build-stage /app/server .

EXPOSE 8080
CMD ["./server"]
