FROM golang:1.16

WORKDIR /usr/src/app

EXPOSE 8080
ENV PORT=8080
ENV REQUEST_ORIGIN=http://localhost:5001

RUN useradd -m appuser

COPY example-backend/go.mod \
     example-backend/go.sum ./

RUN go mod download

COPY example-backend .

RUN go build -o server && \
    chown -R appuser /usr/src/app && \
    rm -rf /root/.cache/go-build

USER appuser

CMD ["./server"]
