FROM node:16-alpine AS build-stage

WORKDIR /app

COPY example-frontend/package*.json ./
RUN npm install

COPY example-frontend .
RUN npm run build


FROM node:16-alpine

WORKDIR /app

RUN npm install -g serve

COPY --from=build-stage /app/build ./build

EXPOSE 5001
CMD ["serve", "-s", "build", "-l", "5001"]
