FROM node:16

WORKDIR /usr/src/app

RUN useradd -m appuser

EXPOSE 5001
ENV REACT_APP_BACKEND_URL=http://localhost:8080

COPY example-frontend/package*.json ./

RUN npm install

COPY example-frontend .
RUN npm install -g serve
RUN npm run build

RUN chown -R appuser /usr/src/app

USER appuser

CMD ["serve", "-s", "-l", "5001", "build"]
